### PR TITLE
General fixes

### LINKED ISSUE #336: Rename the instance folder when renaming instances
What the title says.

### LINKED ISSUE #689: MultiMC creates imgur albums even when uploading single screenshots

### LINKED ISSUE #1663: Oversized instance icons can cause failure
## System Information

MultiMC version: 0.4.11 (with libxcb.so.1 linked from OS)

Operating System: Kubuntu 16.04
## Summary of the issue or suggestion:

Other packs run fine, this one with the icon implodes.
## What should happen:

Click mouse - run modpack
## Steps to reproduce the issue (Add more if needed):
1. Download Vazkii's curse downloader https://github.com/Vazkii/CMPDL/releases
2. Use it to download https://minecraft.curseforge.com/projects/universal-interdimensional-escape
3. Make an empty 1.7.10 instance, install Forge (the downloader tells the version required)
4. Run the instance once and quit.
5. Locate the directory made by the downloader, and copy it's contents into the instance folder. Bluntly overwrite the contents.
6. Download the pack icon from the page on curse (hint:  use your browser's dev tools). Rename it to the pack name (with spaces or without, removing the spaces doesn't change the result).
7. Click on the default icon in the right-hand column to change it. Add new, select the downloaded image. Re-select it in the icon chooser. Accept it.
8. Try to run the pack. MultiMC implodes with the log below.
## Suspected cause:

Packaged libs, duh /s

Image thingamajig.
## Logs/Screenshots:

```
  204.692 W QWidget::setLayout: Attempting to set QLayout "" on ConsoleWindow "", which already has a layout
  204.727 D Task succeeded
  204.727 D Task succeeded
  204.727 D Task succeeded
  204.727 D Instance either provides a version file or doesn't need an update.
  204.727 D "Universal: Interdimensional Escape" : downloading libraries
  204.727 W Order file doesn't exist. Ignoring.
  204.727 D Reading "net.minecraftforge.json"
  204.728 D "Libraries for instance Universal: Interdimensional Escape"  started.
  204.729 W The X11 connection broke: Maximum allowed requested length exceeded (code 4)
XIO:  fatal IO error 2 (Nie ma takiego pliku ani katalogu) on X server ":0"
      after 3648 requests (3648 known processed) with 0 events remaining.
```
## Additional Info:

Message if you would like to receive the ready pack (do not want to publicly redistribute it).

### LINKED ISSUE #1701: Insemnificant Issue | When updating one file, it says updating 1 files
## System Information

MultiMC version: 0.4.10-develop-834

Operating System: Windows 7 Professional x64
## Summary of the issue or suggestion:

When the update box appears, if only 1 file needs to be updated, it says "Downloading 1 update files", instead of file. This isn't really an issue, but its a thing I've noticed

### LINKED ISSUE #1813: Truncation of text in configs by '#': it should be escaped when writing strings
System Information
-----------------------------
MultiMC version: 0.5.0 build 929 

Operating System: Windows 7 SP 1

Summary of the issue or suggestion:
----------------------------------------------
Entering a pound (#) sign in the notes and restarting MultiMC causes the # sign and everything after it to be deleted.

Reproducible.

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

### LINKED ISSUE #2065: MultiMC should strip unicode characters from instance folder names
System Information
-----------------------------
MultiMC version:newest

Operating System: win10

Summary of the issue or suggestion: it is able to run on my computer but cant even open on my friend's laptop
----------------------------------------------

What should happen: run well
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.open it

2.

3.

Suspected cause: I don't know
---------------------------

Logs/Screenshots:
MultiMC version: 0.5.2-1096

Minecraft folder is:
instances/The World第二资料片发布！沉浸在养老中吧/minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_131/bin/javaw.exe

检查Java版本...
Java版本1.8.0_131, 在64-bit架构上

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  D:/minecraft/MultiMC/instances/The World第二资料片发布！沉浸在养老中吧/natives

Libraries:
  D:/minecraft/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  D:/minecraft/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  D:/minecraft/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/minecraft/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/minecraft/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/minecraft/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/minecraft/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  D:/minecraft/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  D:/minecraft/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  D:/minecraft/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  D:/minecraft/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  D:/minecraft/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  D:/minecraft/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  D:/minecraft/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  D:/minecraft/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  D:/minecraft/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  D:/minecraft/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  D:/minecraft/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  D:/minecraft/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  D:/minecraft/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  D:/minecraft/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  D:/minecraft/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  D:/minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  D:/minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  D:/minecraft/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  D:/minecraft/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/minecraft/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  D:/minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  D:/minecraft/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1558-1.7.10/forge-1.7.10-10.13.4.1558-1.7.10-universal.jar
  D:/minecraft/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  D:/minecraft/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  D:/minecraft/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  D:/minecraft/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  D:/minecraft/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  D:/minecraft/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  D:/minecraft/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  D:/minecraft/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  D:/minecraft/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  D:/minecraft/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  D:/minecraft/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  D:/minecraft/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  D:/minecraft/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  D:/minecraft/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  D:/minecraft/MultiMC/versions/1.7.10/1.7.10.jar
  D:/minecraft/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  D:/minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar
  D:/minecraft/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  D:/minecraft/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  Enchiridion 2-1.7.10-2.0.2a
  í++·¦íí+¦G+¦¦----ShadersModCore-v2.3.31-mc1.7.10-f (1)
  í+Bulidí++S++2-Chisel2-2.5.1.44
  í+Factoryí+¦8+½-ª-+-ProjectRed-1.7.10-4.7.0pre12.95-Base
  í+Factoryí+¦8+½-ª-+-ProjectRed-1.7.10-4.7.0pre12.95-Compat
  í+Factoryí+¦8+½-ª-+-ProjectRed-1.7.10-4.7.0pre12.95-Fabrication
  í+Factoryí+¦8+½-ª-+-ProjectRed-1.7.10-4.7.0pre12.95-Integration(1)
  í+Factoryí++¿+¦++-(-+n-˜¦_¦+-logisticspipes-0.9.3.100
  í+Factoryí++¿+¦7-buildcraft-7.1.17
  í+Factoryí++ª++-_+¦++-(-+n¦a¦ó¦µExtraCells-1.7.10-2.3.14b197
  í+Factoryí++ª++-_+¦-appliedenergistics2-rv3-beta-5
  í+Foodí+¦+¦v-¦¦F-AppleMilkTea2-1.7.10_2.9m
  í+Foodí++¬-¦¦ñ-+-AgriCraft-1.7.10-1.5.0
  í+Foodí++·+e¦˜+¦---SpiceOfLife-mc1.7.10-1.3.1
  í+Foodí++dG+-T-cookingbook-mc1.7.10-1.0.140
  í+Foodí++--f-¦-Pam's HarvestCraft 1.7.10k
  í+Foodí++ó¦÷+-+n-HungerOverhaul-1.7.10-1.0.0
  í+Gení++µ-¦-++t+·¦+-5DRTG-1.7.10-1.1.1-CN
  í+Gení+ClimateControl-0.6.beta59
  í+Helpí+¦°+T++++-ChickenChunks-1.7.10-1.3.4.16-universal
  í+Helpí+¦½---T-warpbook-1.7.10_2.0.36
  í+Helpí+¦s+f+++T-Clearing Block Mod-0.3
  í+Helpí+-+--¦+-+-journeymap-1.7.10-5.1.4p1-unlimited
  í+Helpí++±++-¦¦·+¦+n-º+¿-¦-¦+=-TCBotaniaExoflame-1.7.10-1.2
  í+Helpí++8-++»++-FastLeafDecay-1.7.10-1.4
  í+Helpí+AOBD-2.9.1
  í+Magic&Factoryí++±++&+ª++++-(-+±++-_+¦-thaumicenergistics-1.0.0.5
  í+Magicí++¦+n-º+¿-Botania r1.8-249
  í+Magicí+++¦p++++¦˜-tcnodetracker-1.7.10-1.0.4
  í+Magicí++±++-¦¦·++-(-¦G+˜+«¦¡-IlluminatedBows-1.7.10-1.7.1f
  í+Magicí++±++-¦¦·++-(-++¦»+»-º+¿-Automagy-1.7.10-0.28.2
  í+Magicí++±++-¦¦·++-(-+±++¦+-+ThaumicExploration-1.7.10-1.1-55
  í+Magicí++±++-¦¦·++-(-+±++¦ñ+¦r-2.5-1.7.10-164
  í+Magicí++±++-¦¦·++-(-+±++-++t-thaumichorizons-1.7.10-1.1.9
  í+Magicí++±++-¦¦·++-(-+±+++·¦í-º-ThaumicBases-1.3.1710.4
  í+Magicí++±++-¦¦·++-(-+v++-º+¿Forbidden Magic-1.7.10-0.575
  í+Magicí++±++-¦¦·+G¦µ+¿+F-tcinventoryscan-mc1.7.10-1.0.10
  í+Magicí++±++-¦¦·-Thaumcraft-1.7.10-4.2.3.5 (1)
  í+Storageí+¦ó¦µ¦T¦d--+-¦-++¦StorageDrawers-Forestry-1.7.10-1.1.2
  í+Storageí+¦ó¦µ¦T¦d-StorageDrawers-1.7.10-1.10.0
  í+Storageí++¦¦¦++++RemoteIO-1.7.10-2.3.B0-universal
  í+survivalí++¬-¼-G++-CoroUtil-1.1.1
  í+survivalí++¬-¼-G++-ZombieAwareness-1.9.6
  í+Technologyí+-_-++¬+»-PowerUtils-1.7.10-1.0.4[¦¦+»]
  í+Technologyí+-¦-¦-Galacticraft-Planets-1.7-3.0.12.464
  í+Technologyí+-¦-¦-GalaxySpace-1.1.0 STABLE
  í+Technologyí+¦+¦í+¦++-magneticraft-0.6.1-final
  í+Technologyí+¦·-+-Railcraft_1.7.10-9.10.0.0
  í+Technologyí+¦ñ-¦++-(--+-¦-forestry_1.7.10-4.2.2.50
  í+Technologyí+¦ñ-¦2-industrialcraft-2-2.2.684-experimental
  í+Technologyí++n¦a++---MoreFuel-1.0
  í+Toolí+¦----²+¦-+-+¦s+¦
  í+Toolí++¦+O++-(-+¦+O-¦++¦º-TSteelworks-1.7.10-1.1.2-20
  í+Toolí++¦+O++-(-+¦+O++++-tinker_io-1.7.10-release 1.5.0
  í+Toolí++¦+O+°++-TinkersTailor-alpha-0.3.0
  í+Toolí++¦+O-TConstruct-1.7.10-1.8.8
  í+Toolí+=ß=µ+÷¦+-IguanaTinkerTweaks-1.7.10-2.1.5
  ImmersiveEngineering-0.7.7
  mod_voxelMap_1.5.20_for_1.7.10
  TofuCraft-1.6.14-MC1.7.2

Params:
  --username  --version MultiMC5 --gameDir D:/minecraft/MultiMC/instances/The World第二资料片发布！沉浸在养老中吧/minecraft --assetsDir D:/minecraft/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx4096m, -Duser.language=en]

Minecraft进程ID：4996

Using onesix launcher.

[14:21:27] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[14:21:27] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[14:21:27] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[14:21:27] [main/INFO] [FML]: Forge Mod Loader version 7.99.36.1558 for Minecraft 1.7.10 loading
[14:21:27] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_131, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_131
[14:21:27] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/WARN] [FML]: The coremod DummyCore.ASM.DCLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/WARN] [FML]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.DepLoader$DepLoadInst:<init>:333]: MicdoodleCore searching for dependencies in mods file: D:\minecraft\MultiMC\instances\The World???????????????\minecraft\mods
[14:21:28] [main/WARN] [FML]: The coremod mrtjp.core.handler.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/WARN] [FML]: The coremod ak.potionextension.asm.PotionExtensionCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/WARN] [FML]: The coremod tsuteto.tofu.asm.TofuCraftCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/WARN] [FML]: The coremod lumien.nonausea.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/WARN] [FML]: The coremod lain.mods.inputfix.InputFix does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/WARN] [FML]: The coremod fastcraft.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/INFO] [FML]: Loading tweaker me.guichaguri.betterfps.tweaker.BetterFpsTweaker from í++·¦íí++n¦+¦-FPS-Ex-BetterFps-1.0.1.jar
[14:21:28] [main/WARN] [FML]: The coremod nce.nceCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from í++·¦íí++¯¦s-¦+¦-OptiFine_C1[hukk¦¦+»].jar
[14:21:28] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/INFO] [FML]: Loading tweaker shadersmodcore.loading.SMCTweaker from í++·¦íí+¦G+¦¦----ShadersModCore-v2.3.31-mc1.7.10-f (1).jar
[14:21:28] [main/INFO] [FML]: [AppEng] Core Init
[14:21:28] [main/WARN] [FML]: The coremod logisticspipes.asm.LogisticsPipesCoreLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/WARN] [FML]: The coremod mods.defeatedcrow.asm.AppleMilkCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/WARN] [FML]: The coremod thaumic.tinkerer.preloader.ThaumicTLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/WARN] [FML]: The coremod thaumcraft.codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/WARN] [FML]: The coremod remoteio.core.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/INFO] [FML]: Loading tweaker forestry.shade.javacheck.Java7Checker from í+Technologyí+¦ñ-¦++-(--+-¦-forestry_1.7.10-4.2.2.50.jar
[14:21:28] [main/WARN] [FML]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:21:28] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:21:28] [main/INFO] [LaunchWrapper]: Loading tweak class name me.guichaguri.betterfps.tweaker.BetterFpsTweaker
[14:21:28] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[14:21:28] [main/INFO] [LaunchWrapper]: Loading tweak class name shadersmodcore.loading.SMCTweaker
[14:21:28] [main/INFO] [LaunchWrapper]: Loading tweak class name forestry.shade.javacheck.Java7Checker
[14:21:28] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[14:21:28] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:21:28] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:21:28] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[14:21:28] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: acceptOptions
[14:21:28] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: injectIntoClassLoader
[14:21:28] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ClassTransformer
[14:21:28] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine URL: file:/D:/minecraft/MultiMC/instances/The%20World???????????????/minecraft/mods/1.7.10/í++·¦íí++¯¦s-¦+¦-OptiFine_C1%5Bhukk¦¦+»%5D.jar
[14:21:28] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ZIP file: java.util.zip.ZipFile@302552ec
[14:21:28] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:28] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:29] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[14:21:30] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:30] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:102]: Successfully Registered Transformer
[14:21:30] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[14:21:30] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:31] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:31] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:31] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:31] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:31] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:31] [main/INFO] [RemoteIO:ASM]: Adding transformer for: [net.minecraft.client.renderer.Tessellator]
[14:21:31] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:31] [main/INFO] [IC2-core]: Loaded library ejml-0.23.jar.
[14:21:31] [main/INFO] [LaunchWrapper]: Calling tweak class forestry.shade.javacheck.Java7Checker
[14:21:31] [main/INFO] [LaunchWrapper]: Calling tweak class me.guichaguri.betterfps.tweaker.BetterFpsTweaker
[14:21:31] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[14:21:31] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:31] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:31] [main/INFO] [LaunchWrapper]: Calling tweak class shadersmodcore.loading.SMCTweaker
[14:21:31] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:31] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:21:31] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[14:21:31] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[14:21:31] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: getLaunchArguments
[14:21:31] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[14:21:31] [main/INFO] [me.guichaguri.betterfps.transformers.EventTransformer]: Patching Game Start...
[SMC FNE]transforming bao net.minecraft.client.Minecraft
[SMC FNE] 77697 (+59)
[14:21:31] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: ahb (1 / 1)
[14:21:31] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: sv (1 / 1)
[14:21:31] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: sa (1 / 1)
[14:21:31] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: bdi (1 / 1)
[14:21:31] [main/INFO] [AE2-CORE]: func_146977_a(Lnet/minecraft/inventory/Slot;)V - Transformed
[14:21:31] [main/INFO] [AE2-CORE]: func_146977_a_original(Lnet/minecraft/inventory/Slot;)V - New Method
[14:21:31] [main/INFO] [AE2-CORE]: func_146977_a(Lnet/minecraft/inventory/Slot;)V - Invoke Virtual
[14:21:32] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: D:\minecraft\MultiMC\instances\The World???????????????\natives\lwjgl.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadLibrary0(Unknown Source) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:1.8.0_131]
	at java.lang.Runtime.load0(Unknown Source) ~[?:1.8.0_131]
	at java.lang.System.load(Unknown Source) ~[?:1.8.0_131]
	at org.lwjgl.Sys$1.run(Sys.java:70) ~[lwjgl-2.9.1.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.Sys.loadLibrary(Sys.java:95) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.Sys.<clinit>(Sys.java:112) ~[lwjgl-2.9.1.jar:?]
	at net.minecraft.client.Minecraft.func_71386_F(Minecraft.java:2671) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 14 more
[14:21:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:239]: Failed to start Minecraft:
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:53)
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.System.exit(Unknown Source)
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 8 more
[14:21:32] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:56]: Exiting with -1
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ArrayIndexOutOfBoundsException: 5
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.System.exit(Unknown Source)
[14:21:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:57)
Exception in thread "main" 
进程退出，代码：1。
Clipboard copy at: 11 Dec 2017 14:25:12 -0800

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
进程退出，代码：1。means it is closed and and code is 1
---------------------------

### LINKED ISSUE #2499: Proxies should apply instantly
System Information
-----------------------------
MultiMC version: latest develop (0.6.2-1283)

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
If I change proxy settings, I need to restart MultiMC. This is pretty confusing, because it's noted nowhere and people could assume proxies don't work (like in #1967).

What should happen:
------------------------------
The change instantly applies

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Setup a non-existing proxy and restart MultiMC

2. Remove the proxy

3. Try to download anything

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

### LINKED ISSUE #2515: Deleting an instance externally with deletion confirmation open deletes another pack
System Information
-----------------------------
MultiMC version: 0.6.4-1291

Operating System: Windows 10 (10.0.16299)

Summary of the issue or suggestion:
----------------------------------------------
Upon deleting a pack, if the deletion confirmation is accepted after the pack is deleted externally, another pack will be deleted in its place.

What should happen:
------------------------------
An error or similar event preventing the deletion of the "innocent" pack.

Steps to reproduce the issue:
-------------------------------------------------------------
1. Open the deletion confirmation for a pack

2. Delete the pack externally, then confirm the dialog

3. Another pack will be deleted in its place.

Suspected cause:
---------------------------
Something in InstanceList::deleteInstance, but I can't seem to find the bug. Unless getInstanceById returning an empty InstancePtr can somehow coincide with an existing instance. 

Additional Info:
---------------------------
Looking through my logs, I don't see anything that has the debug strings found in InstanceList::deleteInstance, unless it has been overwritten; I've opened MultiMC a few times since the scare (I had a backup of the instance thankfully)

### LINKED ISSUE #2552: Make change version dialogue great again!
Change Minecraft version dialogue not unified with the create instance one with having the filter.

image
image

### LINKED ISSUE #2584: Ridiculously large icons crash the application (2000x2000)
System Information
-----------------------------
MultiMC version: 0.6.5-1217

Operating System: Ubuntu 18.04.2 LTS

Summary of the issue or suggestion:
----------------------------------------------
MultiMC crashes when I try to edit or run the instance of Enigmatica2 1.63a. With the icon from the Curse modpack page ( https://media.forgecdn.net/avatars/191/824/636861646865159125.png )

Happens both on a old and a fresh (only the `instances` directory is symlinked from the old one) instance of MultiMC

What should happen:
------------------------------
The "Edit Instance" window should appear or the instance should start.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download the pack zip from https://minecraft.curseforge.com/projects/enigmatica2/files/2691579
2. Install the zip trough MultiMC new instance dialog.
3. Download the pack avatar from Curse (you need to use the element inspector).
4. Add the avatar as the pack icon.
5. Try to launch or edit the instance.

Suspected cause:
---------------------------
Unknown. My guesses would be on a mangled/malicious PNG or a library edge-case.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
This is a log between clicking on "Edit Instance" and crashing:
```
    4.779 D Task "ComponentUpdateTask(0x2b77e30)" starting for the first time
    4.780 D Loading components
    4.780 D Task "NetJob(Download of meta file index.json)" starting for the first time
    4.780 D Remote loading is being run for metadata index
    4.781 D Task "NetJob(Download of meta file net.minecraft/1.12.2.json)" starting for the first time
    4.781 D Remote loading is being run for "net.minecraft"
    4.781 D Task "NetJob(Download of meta file net.minecraftforge/14.23.5.2781.json)" starting for the first time
    4.781 D Remote loading is being run for "net.minecraftforge"
    4.782 D Task "NetJob(Download of meta file net.minecraft/index.json)" starting for the first time
    5.264 C BAD stuff happened to mod json:
    5.264 C "{
  "modListVersion": "2",
  "modList":
  [
    {
      "modid": "openblocks",
      "name": "OpenBlocks",
      "description": "All the things you never thought you will ever need",
      "version": "1.8",
      "mcversion": "1.12.2",
      "url": "http://openmods.info/",
      "updateUrl": "",
      "authorList": [
        "Mikee",
        "NeverCast",
        "boq",
        "Lyqyd"
      ],
      "credits": "",
      "logoFile": "",
      "screenshots": [
      ],
      "parent": ""
    }
  ]
}
"
    5.475 W QMetaObject::connectSlotsByName: No matching signal for on_RunningState_changed(bool)
    5.496 D Applying "net.minecraft" GOOD
    5.496 D Applying "net.minecraftforge" ERROR
    5.584 W The X11 connection broke: Maximum allowed requested length exceeded (code 4)
XIO:  fatal IO error 2 (No such file or directory) on X server ":0"
      after 379 requests (379 known processed) with 0 events remaining.
```

Additional Info:
---------------------------

### LINKED ISSUE #2592: MultiMC doesn't highlight newly created instance
Highlight newly created instances upon being created.

### PR DESCRIPTION
**Pull request by Janrupf**
This pull request fixes a bunch of issues. This includes old and new ones and is as the time of writing not ready yet.

List of affected issues by now:
- closes #2592: New instances are now selected automatically
- fixes #1813: # are no longer getting truncated
- fixes #2515: Externally deleted instances no longer cause the next instance to be deleted when the dialog has already been opened
- closes #336: The user can now select to rename the instance with its folder

UPDATE: All affected issues:
- closes #2592: New instances are now selected automatically
- fixes #1813: # are no longer getting truncated
- fixes #2515: Externally deleted instances no longer cause the next instance to be deleted when the dialog has already been opened
- closes #336: The user can now select to rename the instance with its folder
- fixes #2584, fixes #1663: Icons are now downscaled to 512x512 if they are bigger
- fixes #2065: Everything above char code 127 is now replaced
- closes #689: For single screenshots MultiMC no longer creates albums
- closes #2499: Proxy settings are now applied as soon as the settings are saved
- fixes #1701: MultiMC now checks if the count is 1 and displays a different message if so
- closes #2552: There is now one widget for all version selections

### CODE REVIEW

**Comment by peterix** [comment]
This doesn't pass unit tests.

File: api/logic/settings/INIFile.cpp [hunk 1]
```diff
@@ -28,49 +28,20 @@ INIFile::INIFile()
...
-            {
-                prev = c;
-                continue;
-            }
-            out += c;
-            prev = 0;
-        }
-    }
-    return out;
+    return orig
```
Comment (peterix) [inline api/logic/settings/INIFile.cpp]: Please make this a single pass again. It stops it from working correctly.

File: api/logic/settings/INIFile.cpp [hunk 2]
```diff
@@ -28,49 +28,20 @@ INIFile::INIFile()
...
-            out += "\\n";
-        else if (c == '\t')
-            out += "\\t";
-        else if(c == '\\')
-            out += "\\\\";
-        else
-            out += c;
-    }
-    return out;
+    return orig
```
Comment (peterix) [inline api/logic/settings/INIFile.cpp]: Again, this must be a single pass. Put it back.

File: api/logic/settings/INIFile.cpp [hunk 3]
```diff
@@ -120,7 +91,15 @@ bool INIFile::loadFile(QByteArray file)
     {
         QString &lineRaw = lines[i];
         // Ignore comments.
-        QString line = lineRaw.left(lineRaw.indexOf('#')).trimmed();
+        int commentIndex = 0;
+        QString line = lineRaw;
+        // Search for comments until no more escaped # are available
+        while((commentIndex = line.indexOf('#', commentIndex + 1)) != -1) {
```
Comment (peterix) [inline api/logic/settings/INIFile.cpp]: I'd like to see unit tests for this.

File: application/groupview/InstanceDelegate.cpp [hunk 4]
```diff
@@ -341,82 +342,4 @@ QSize ListViewDelegate::sizeHint(const QStyleOptionViewItem &option,
     return sz;
 }
 
-class NoReturnTextEdit: public QTextEdit
```
Comment (peterix) [inline application/groupview/InstanceDelegate.cpp]: Why is this removed?

Comment (Janrupf) [reply application/groupview/InstanceDelegate.cpp]: Its not used anymore, renaming is now handled via a dialog.

**Comment by Janrupf** [comment]
Now affecting more issues:
- fixes #2584, fixes #1663: Icons are now downscaled to 512x512 if they are bigger
- fixes #2065: Everything above char code 127 is now replaced
- closes #689: For single screenshots MultiMC no longer creates albums

**Comment by Janrupf** [comment]
Now also affecting:
- closes #2499: Proxy settings are now applied as soon as the settings are saved
- fixes #1701: MultiMC now checks if the count is 1 and displays a different message if so
- closes #2552: There is now one widget for all version selections
